Fix clippy warning
raptorswing/rustydht-lib pull request #68
Opened 2022-01-23 21:39 UTC by RRRadicalEdward

Hi! I'm going to use your crate for one of my pet projects. But, while exploring the source code I found that there were a lot of clippy warnings. So I fixed them :slightly_smiling_face:. After fixing, I ran unit tests and no one failed. 
Thank you for the project. I really like the code.

2022-01-24 04:24 UTC, raptorswing requested changes
Thanks very much for this PR. I can tell that you spent some time on it. I wasn't aware of `clippy` before - what a great tool. I'm incorporating it into my workflow from now on.

I have a few small requests for the changes - please take a look.

Thanks again.

2022-01-24 04:24 UTC, raptorswing commented on src/dht/dht_settings.rs
> +        Self::default()
I think we should move the current implementation of `DHTSettings::default()` (lines 76-101) here, then delete `impl DHTSettings {...}` altogether.

```suggestion
        DHTSettings {
            token_secret_size: 10,
            max_peers_response: 128,
            max_sample_response: 50,
            min_sample_interval_secs: 10,
            router_ping_interval_secs: 900,
            reverify_interval_secs: 14 * 60,
            reverify_grace_period_secs: 15 * 60,
            verify_grace_period_secs: 60,
            get_peers_freshness_secs: 15 * 60,
            find_nodes_interval_secs: 33,
            find_nodes_skip_count: 32,
            max_torrents: 50,
            max_peers_per_torrent: 100,
            ping_check_interval_secs: 10,
            outgoing_request_prune_secs: 30,
            outgoing_reqiest_check_interval_secs: 30,
            read_only: false,
            routers: vec![
                "router.bittorrent.com:6881".to_string(),
                "router.utorrent.com:6881".to_string(),
                "dht.transmissionbt.com:6881".to_string(),
            ],
        }
```

2022-01-24 04:24 UTC, raptorswing commented on src/packets/internal.rs
> +    PingResponse {
Please remove `Response` from the end of this variant to be consistent with the others.

```suggestion
    Ping {
```

2022-01-24 04:24 UTC, raptorswing commented on src/dht/socket.rs
> +                        // It's fine if there's no channel - just means that the sender didn't care about getting a response
Please move the comment to be before the `if let`
```suggestion
                        // It's fine if there's no channel - just means that the sender didn't care about getting a response
                        if let Some(response_channel) = request_info.response_channel {
                            if let Err(e) = response_channel.send(message.clone()).await {
                                let message = e.0;
                                warn!(target: "rustydht_lib::DHTSocket", "Got response, but sending code abandoned the channel receiver. So sad. Response: {:?}. Sender: {:?}", message, sender);
                            }
                        }
```

2022-01-24 04:24 UTC, raptorswing commented on src/dht/dht.rs
> +                                    state.buckets.add_or_update(node.clone(), false);
Please preserve the comment so I remember wtf I was thinking 😄 

```suggestion
                        // Special handling for find_node responses
                        // Add the nodes we got back as "seen" (even though we haven't necessarily seen them directly yet).
                        // They will be pinged later in an attempt to verify them.
                        if let packets::ResponseSpecific::FindNodeResponse(args) = response_variant {
                            let mut state = state.lock().unwrap();
                            for node in &args.nodes {
                                if node.id.is_valid_for_ip(&node.address.ip()) {
                                    state.buckets.add_or_update(node.clone(), false);
```

2022-01-24 19:48 UTC, RRRadicalEdward commented on src/dht/dht.rs
> +                                    state.buckets.add_or_update(node.clone(), false);
Done

2022-01-24 19:49 UTC, RRRadicalEdward commented on src/dht/socket.rs
> +                        // It's fine if there's no channel - just means that the sender didn't care about getting a response
Done

2022-01-24 19:49 UTC, RRRadicalEdward commented on src/dht/dht_settings.rs
> +        Self::default()
Done

2022-01-24 19:51 UTC, RRRadicalEdward commented on src/packets/internal.rs
> +    PingResponse {
Done

2022-01-25 04:54 UTC, raptorswing approved these changes
Thanks!

2022-01-25 04:54 UTC, merged